# Generated by Django 2.2.4 on 2019-08-30 23:51

from django.db import migrations, models
import slock.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='User Name', max_length=256, null=True, verbose_name='Name')),
                ('password', models.CharField(help_text='Password', max_length=256, null=True, verbose_name='Password')),
                ('email', models.EmailField(max_length=70, null=True, unique=True)),
            ],
            bases=(slock.models.BasicUserMixin, models.Model),
        ),
    ]
